#!/bin/bash

# Multiple tests for the error-by-layer method 

chmod u+x testSuiteMay1
# python WineQuality_Control_Net.py "Wine_Control_Test" 0.005 1
# python WineQuality_ErrorByLayer.py "Wine_Experimental_Test" 0.005 1 3
# python ../IRIS_Control_Net.py "Iris_Control_Test" 0.005 1
# python ../IRIS_ErrorAlloc_v2.py "Iris_Experimental_Test" 0.005 1 3


python WineQuality_Control_Net.py "Wine_Control_11" 0.02 500 15 15
python WineQuality_ErrorByLayer.py "Wine_Trial_11" 0.02 500 15 15 3 
python WineQuality_Control_Net.py "Wine_Control_12" 0.005 500 20 20
python WineQuality_ErrorByLayer.py "Wine_Trial_12" 0.005 500 20 20 4

