#!/bin/bash

# Multiple tests for the error-by-layer method 

chmod u+x testSuiteMay1
# python WineQuality_Control_Net.py "Wine_Control_Test" 0.005 1
# python WineQuality_ErrorByLayer.py "Wine_Experimental_Test" 0.005 1 3
# python ../IRIS_Control_Net.py "Iris_Control_Test" 0.005 1
# python ../IRIS_ErrorAlloc_v2.py "Iris_Experimental_Test" 0.005 1 3


python WineQuality_Control_Net.py "Wine_Control_1" 0.005 200
python WineQuality_ErrorByLayer.py "Wine_Trial_1" 0.005 200 3
python WineQuality_Control_Net.py "Wine_Control_2" 0.01 200
python WineQuality_ErrorByLayer.py "Wine_Trial_2" 0.01 200 3
python WineQuality_Control_Net.py "Wine_Control_3" 0.005 200
python WineQuality_ErrorByLayer.py "Wine_Trial_3" 0.005 200 4
python WineQuality_Control_Net.py "Wine_Control_4" 0.01 200
python WineQuality_ErrorByLayer.py "Wine_Trial_4" 0.01 200 4


python WineQuality_Control_Net.py "Wine_Control_5" 0.005 200
python WineQuality_ErrorByLayer.py "Wine_Trial_5" 0.005 200 0.5
python WineQuality_Control_Net.py "Wine_Control_6" 0.01 200
python WineQuality_ErrorByLayer.py "Wine_Trial_6" 0.01 200 0.5
python WineQuality_Control_Net.py "Wine_Control_7" 0.005 200
python WineQuality_ErrorByLayer.py "Wine_Trial_7" 0.005 200 1.0
python WineQuality_Control_Net.py "Wine_Control_8" 0.01 200
python WineQuality_ErrorByLayer.py "Wine_Trial_8" 0.01 200 1.0


python ../IRIS_Control_Net.py "Iris_Control_1" 0.005 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_1" 0.005 200 3
python ../IRIS_Control_Net.py "Iris_Control_2" 0.01 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_2" 0.01 200 3
python ../IRIS_Control_Net.py "Iris_Control_3" 0.005 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_3" 0.005 200 4
python ../IRIS_Control_Net.py "Iris_Control_4" 0.01 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_4" 0.01 200 4

python ../IRIS_Control_Net.py "Iris_Control_1" 0.005 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_1" 0.005 200 0.5
python ../IRIS_Control_Net.py "Iris_Control_2" 0.01 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_2" 0.01 200 0.5
python ../IRIS_Control_Net.py "Iris_Control_3" 0.005 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_3" 0.005 200 1.0
python ../IRIS_Control_Net.py "Iris_Control_4" 0.01 200
python ../IRIS_ErrorAlloc_v2.py "Iris_Trial_4" 0.01 200 1.0